apiVersion: v1
kind: Template
labels:
  template: camel-wordpress-sample-template
  project: camel-wordpress-sample-template
metadata:
  annotations:
    description: Camel Wordpress example scenario
    iconClass: icon-php
    tags: microservice,camel,camel-wordpress,wordpress
    author: Ricardo Zanini <ricardozanini@gmail.com>
    url: https://github.com/ricardozanini/camel-example-wordpress
  name: camel-wordpress-sample-template
parameters:
- description: Grab your token in https://www.football-data.org/client/register
  displayName: Football Api Token
  name: FOOTBALL_API_TOKEN
  required: true
  value:
- description: The username of your Wordpress. You have to configure your installation with this user.
  displayName: Wordpress Username
  name: WORDPRESS_USER
  required: true
  value:
- description: The password of your Wordpress user. You have to configure your installation with this password.
  displayName: Wordpress password
  name: WORDPRESS_PASS
  required: true
  value:
- description: MySQL Username
  displayName: MySQL Username
  name: MYSQL_USER
  from: "user[a-zA-Z0-9]{3}"
  generate: expression
- description: MySQL Password
  displayName: MySQL Password
  name: MYSQL_PASSWORD
  from: "[a-zA-Z0-9]{8}"
  generate: expression
objects:
- apiVersion: v1
  data:
    football-api-token: ${FOOTBALL_API_TOKEN}
    wordpress-password: ${WORDPRESS_PASS}
  kind: Secret
  metadata:
    labels:
      app: camel-soccer-news
    name: camel-soccer-news
  type: Opaque
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: camel-soccer-news
    name: camel-soccer-news
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: wordpress
    name: wordpress-img
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: wordpress
    name: wordpress-s2i
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: camel-soccer-news
    name: camel-soccer-news
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: camel-soccer-news:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/ricardozanini/camel-example-wordpress
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: wordpress
    name: wordpress-img
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: wordpress-img:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/wordpress4j/Basic-Auth
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: wordpress-s2i:latest
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: wordpress
    name: wordpress-s2i
  spec:
    nodeSelector: null
    output:
      imageLabels:
      - name: io.k8s.display-name
        value: WordPress
      - name: io.k8s.description
        value: WordPress application and S2I builder.
      - name: io.openshift.s2i.scripts-url
        value: image:///opt/app-root/s2i
      - name: io.s2i.scripts-url
        value: image:///opt/app-root/s2i
      - name: io.openshift.tags
        value: builder,php,wordpress
      to:
        kind: ImageStreamTag
        name: wordpress-s2i:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/openshift-evangelists/wordpress-quickstart
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:5.6
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: camel-soccer-news
    name: camel-soccer-news
  spec:
    replicas: 1
    selector:
      deploymentconfig: camel-soccer-news
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: camel-soccer-news
          deploymentconfig: camel-soccer-news
      spec:
        containers:
        - env:
          - name: WORDPRESS_URL
            value: http://wordpress:8080/wp-json
          - name: FOOTBALL_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: football-api-token
                name: camel-soccer-news
          - name: WORDPRESS_PASS
            valueFrom:
              secretKeyRef:
                key: wordpress-password
                name: camel-soccer-news
          - name: WORDPRESS_USER
            value: ${WORDPRESS_USER}
          image: camel-soccer-news
          imagePullPolicy: Always
          name: camel-soccer-news
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - camel-soccer-news
        from:
          kind: ImageStreamTag
          name: camel-soccer-news:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: wordpress
    name: wordpress
  spec:
    replicas: 1
    selector:
      app: wordpress
      deploymentconfig: wordpress
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: wordpress
          deploymentconfig: wordpress
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_HOST
            value: wordpress-db
          - name: MYSQL_TABLE_PREFIX
            value: wp_
          image: wordpress-img
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              path: /wp-admin/install.php
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: wordpress
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              path: /wp-admin/install.php
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/app-root/src
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wordpress-wordpress-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wordpress
        from:
          kind: ImageStreamTag
          name: wordpress-img:latest
          namespace: camel-wordpress
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: wordpress
    name: wordpress-db
  spec:
    replicas: 1
    selector:
      app: wordpress
      deploymentconfig: wordpress-db
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: wordpress
          deploymentconfig: wordpress-db
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          image: rhscl/mysql-57-rhel7
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wordpress-mysql-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:5.7
          namespace: openshift
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: camel-soccer-news
    name: camel-soccer-news
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: camel-soccer-news
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wordpress
    name: wordpress
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wordpress
      deploymentconfig: wordpress
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wordpress
    name: wordpress-db
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: wordpress
      deploymentconfig: wordpress-db
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: camel-soccer-news
    name: camel-soccer-news
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: camel-soccer-news
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: wordpress
    name: wordpress
  spec:
    port:
      targetPort: 8080
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: wordpress
      weight: 100
    wildcardPolicy: None